### ISSUE TITLE
"gene regeneration timer will be reset" on serums

### ISSUE THREAD

**Issue by hjkFace** [WVCSergkart/WVC_RacesBiotech#2]
I see "If the user's genes are regrowing, then instead of applying the xenotype, the gene regeneration timer will be reset." on some serums, but you can't use them when genes are regrowing, which defeats the purpose. The option to use them is grayed out, with a hint that genes are regrowing.

**Comment by WVCSergkart** [comment]
This was never their intended purpose. But it can be used anyway if you manually set it as surgery. Select the desired serum and click on the "Administer serum" gizmo.

**Comment by hjkFace** [comment]
It's a nice hint while the fix for gene restoration serum is not up, thank you.

**Comment by hjkFace** [comment]
oh, there is no operation bill option. You can implant from serum itself, but operation aborts with a hint at the top of the screen about genes regrowing and in the end nothing changes

**Comment by WVCSergkart** [comment]
Hmm... Okay, I'll take a look later.
